# Generated by Django 2.1.7 on 2019-04-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item_Spec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cus_I', models.CharField(default='', max_length=32, verbose_name='Cus_I')),
                ('Item_I', models.CharField(default='', max_length=64, verbose_name='Item_I')),
            ],
        ),
        migrations.CreateModel(
            name='Project_Spec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Cus_P', models.CharField(default='', max_length=32, verbose_name='Cus_P')),
                ('Project_P', models.CharField(default='', max_length=32, verbose_name='Project_P')),
                ('Phase_P', models.CharField(default='', max_length=20, verbose_name='Phase_P')),
                ('Item_P', models.ManyToManyField(to='rbac.Item_Spec')),
                ('Owner_P', models.ManyToManyField(to='rbac.UserInfo')),
            ],
        ),
    ]
