# Generated by Django 2.1.7 on 2019-04-24 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_item_spec_project_spec'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': 'UserInfo', 'verbose_name_plural': 'UserInfo'},
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='nickname',
            new_name='account',
        ),
    ]
