# Generated by Django 2.1.7 on 2019-04-25 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0003_auto_20190424_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_spec',
            name='Item_I',
            field=models.CharField(default='', max_length=200, verbose_name='Item_I'),
        ),
    ]
