# Generated by Django 2.1.7 on 2019-04-25 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0004_auto_20190425_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_spec',
            name='Item_Description',
            field=models.CharField(default='', max_length=200, verbose_name='Item_Description'),
        ),
    ]
