# Generated by Django 2.1.7 on 2019-04-25 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0005_item_spec_item_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='item_spec',
            name='Category',
            field=models.CharField(default='', max_length=20, verbose_name='Catgory'),
        ),
    ]
