# Generated by Django 2.1.7 on 2019-04-25 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0006_item_spec_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='permission',
            name='Proj_perm',
            field=models.ManyToManyField(to='rbac.Project_Spec'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='url',
            field=models.CharField(default='', max_length=128, unique=True),
        ),
    ]
