# Generated by Django 2.1.7 on 2019-04-25 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0007_auto_20190425_1434'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item_spec',
            name='Category',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='Catgory'),
        ),
    ]
