# Generated by Django 2.1.7 on 2019-04-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0008_auto_20190425_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='url',
            field=models.CharField(default='', max_length=128, null=True),
        ),
    ]
