# Generated by Django 2.1.7 on 2019-04-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0009_auto_20190425_1547'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='perm',
            field=models.ManyToManyField(to='rbac.Permission'),
        ),
    ]
