# Generated by Django 2.1.7 on 2019-04-25 08:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0010_userinfo_perm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='roles',
        ),
    ]
