# Generated by Django 2.1.7 on 2019-04-16 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Project', models.CharField(default='', max_length=100, verbose_name='Project')),
                ('Unit', models.CharField(default='', max_length=100, verbose_name='Unit')),
                ('Phase', models.CharField(default='', max_length=10, verbose_name='Phase')),
                ('Testitem', models.CharField(default='', max_length=100, verbose_name='Testitem')),
                ('Comments', models.CharField(default='', max_length=1000, verbose_name='Comments')),
                ('Start_time', models.CharField(default='', max_length=26, verbose_name='Start_time')),
                ('End_time', models.CharField(default='', max_length=26, verbose_name='End_time')),
            ],
            options={
                'verbose_name': 'TestLog',
                'verbose_name_plural': 'TestLog',
            },
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Account', models.CharField(default='', max_length=20, verbose_name='Account')),
                ('Password', models.CharField(default='', max_length=256, verbose_name='Password')),
                ('Username', models.CharField(default='', max_length=20, unique=True, verbose_name='Username')),
            ],
            options={
                'verbose_name': 'UserInfo',
                'verbose_name_plural': 'UserInfo',
            },
        ),
        migrations.AddField(
            model_name='testlog',
            name='Tester',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app1.UserInfo', to_field='Username'),
        ),
    ]
