# Generated by Django 2.1.7 on 2019-04-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testlog',
            name='Customer',
            field=models.CharField(default='', max_length=10, verbose_name='Customer'),
        ),
    ]
